Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -83,13 +83,13 @@ jobs:
           path: main/${{ env.ARTIFACTS-SRC-PATH }}
           key: ${{ github.sha }}
       - name: check continue
+        if: steps.cache.outputs.cache-hit  == 'true'
         id: check-continue
         run: |
-          echo "continue=true" >> $GITHUB_OUTPUT
-          cat main/artifacts/head.txt
-          ${{ steps.cache.outputs.cache-hit  == 'true'  }} && echo "ARTIFACTS=$(cat main/artifacts/head.txt)" >> $GITHUB_ENV || echo "::notice title=Cache:: not found"
-          echo ${{ env.ARTIFACTS }}
-          ${{ steps.cache.outputs.cache-hit  == 'true' && env.ARTIFACTS != '' }} && echo "continue=false" >> $GITHUB_OUTPUT || echo "::notice title=Artifacts:: not found" 
+          echo "::notice title=Cache:: found cache, head: $(cat main/artifacts/head.txt)"
+          echo "continue=false" >> $GITHUB_OUTPUT 
+          #${{ steps.cache.outputs.cache-hit  == 'true'  }} && echo "ARTIFACTS=$(cat main/artifacts/head.txt)" >> $GITHUB_ENV || echo "::notice title=Cache:: not found"
+          #${{ steps.cache.outputs.cache-hit  == 'true' && env.ARTIFACTS != '' }} && echo "continue=false" >> $GITHUB_OUTPUT || echo "::notice title=Artifacts:: not found" 
           
   build:
     name: build
