Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -76,12 +76,8 @@ jobs:
       - name: check continue
         id: check-continue
         run: |
-          ${{ steps.cache.outputs.cache-hit  == 'true'  }} && echo "ARTIFACTS=$(cat main/artifacts/head.txt)" >> $GITHUB_ENV || echo "continue"
+          ${{ steps.cache.outputs.cache-hit  == 'true'  }} && echo "ARTIFACTS=$(cat main/artifacts/head.txt)" >> $GITHUB_ENV || echo "::notice title=BUILD SKIPPED>cache not found"
           ${{ steps.cache.outputs.cache-hit  == 'true' && env.ARTIFACTS != '' }} && "continue=false" >> $GITHUB_OUTPUT || echo "continue=true" >> $GITHUB_OUTPUT 
-      - name: annotation
-        if: steps.check-continue.outputs.continue == 'false'
-        run: |
-          echo "::notice title=BUILD SKIPPED>cache found, will skip the build process"
 
           
   build:
