Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -73,7 +73,8 @@ jobs:
           cd main
           gh extension install actions/gh-actions-cache
           echo "CACHE=$(gh cache list | grep ${{ github.sha }})" >> $GITHUB_ENV
-          ${{ env.CACHE == '' }} && echo cache-hit="true" >> $GITHUB_OUTPUT || echo "::notice title=Cache:: not found" 
+          ${{ env.CACHE == '' }} && echo cache-hit="true" >> $GITHUB_OUTPUT || echo "::notice title=Cache:: not found"
+          echo cache-hit="false" >> $GITHUB_OUTPUT
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - name: check continue
